CREATE TABLE SETTINGS(NAME VARCHAR(100), DESCRIPTION VARCHAR(200), VALUE VARCHAR(200),CHANGED TIMESTAMP);

CREATE TABLE MAPPING(MAPITEMID INT IDENTITY, MESSAGEID VARCHAR(50), SOURCE VARCHAR(100), TARGET VARCHAR(100), TARGETLEN INT, NAMESPACEID VARCHAR(20), PARENTID VARCHAR (100), ISBOOLEAN BOOLEAN);

CREATE TABLE REPORTS(REPORTID INT IDENTITY, NAME VARCHAR(100), DESCRIPTION VARCHAR(200), PRODUCED TIMESTAMP, MIMETYPE VARCHAR(50), DATA BLOB);

CREATE TABLE RUNS(RUNID INT IDENTITY, MAPTYPEID INT, START TIMESTAMP, END TIMESTAMP);

CREATE TABLE RUNITEMS(RUNITEMID INT IDENTITY, RUNID INT, MSGNAME VARCHAR(50),PRODUCED BOOLEAN, TIMEPRODUCED TIMESTAMP, LOADED BOOLEAN, TIMELOADED TIMESTAMP);

CREATE TABLE NAMESPACE(NAMESPACEID VARCHAR(20) NOT NULL, NAME VARCHAR(200), CHARPRESENT VARCHAR(1));

CREATE TABLE NAMESPACEMAP(MAPID INT IDENTITY,NAMESPACEID INT, MAPTYPEID INT);

CREATE TABLE MESSAGE(NAME VARCHAR(50), TINAME VARCHAR(50), DESCRIPTION VARCHAR(250));